services:
  - type: web
    name: localizacao-nfc
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: LOCATION_TTL_MINUTES
        value: "60"